### ISSUE TITLE
Is it possible to reposition the spinner ?

### ISSUE THREAD

**Issue by ricardoccpaiva** [MurhafSousli/ng2-progressbar#2]
Is there any way of specifying a custom css class to adjust the spinner position ?

Thanks !

**Comment by MurhafSousli** [comment]
Hi @ricardoccpaiva, you can override the style the way you want, check its [css](https://github.com/MurhafSousli/ng2-progressbar/blob/master/src/ng-progress-bar/ng-progress-bar.component.css)

```css
.spinner {
   display: block;
   position: fixed;
   z-index: 1031;
   top: 15px;
   right: 15px;
}
```
if changes didn't apply, use `!important` to force overriding
