### ISSUE TITLE
Unable to override "top" property in .spinner class

### ISSUE THREAD

**Issue by contactb2** [MurhafSousli/ng2-progressbar#22]
Unable to override "top" property in .spinner class

**Comment by MurhafSousli** [comment]
@contactb2 how are you overriding it?

**Comment by MurhafSousli** [comment]
in your global style 
```css
.spinner{
  top: 15px !important;
  right: 15px !important;
}
```
